### PR TITLE
Finished Multi DatePicker

### PR DESCRIPTION
**Pull request by abaskeraddir**
Supports different date formats and some customization.

### CODE REVIEW

**Comment by Shama95** [comment]
1. add documentation to input variables.
2.  add default variables values.
3. change CalcMaxDate to be a date and not a function.

**Comment by Shama95** [comment]
1. add explaination for usestate in the input function
2. in the date picker change so that when the format is lower option, you can still have an easier time changing the upper options.
3. change name of picker text to placehldertext.

**Comment by abaskeraddir** [comment]
@Shama95 I added all the changes and changed the libraries so the new design works without loosing functionality.
so when you test stuff, don't forget to pull the changes and 'npm install' to install the latest changes.

**Comment by Shama95** [comment]
well done, approved for merge!!!

**Pull request merged**
